# RDS module — MySQL 8.0 instance in private subnets.
#
# The DB password is auto-generated by Terraform and stored in AWS Secrets Manager.
# It never appears in .tfvars or is committed to source control.
#
# The Worker pod retrieves the password at startup via IRSA + Secrets Manager.
# See INSTRUCTIONS.md step 7 for how to sync the secret into a Kubernetes Secret.

terraform {
  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

# ─── Password ─────────────────────────────────────────────────────────────────

# Terraform generates and owns the password. Changing it rotates the RDS password.
resource "random_password" "db" {
  length           = 20
  special          = true
  # Exclude characters that cause issues in JDBC URLs or shell scripts
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

# ─── Secrets Manager ──────────────────────────────────────────────────────────

resource "aws_secretsmanager_secret" "db" {
  name                    = "digital-library/${var.environment}/db-password"
  description             = "RDS MySQL credentials for the ${var.environment} environment"
  recovery_window_in_days = 7 # allow recovery for 7 days after deletion

  tags = {
    Name        = "digital-library-db-${var.environment}"
    Environment = var.environment
  }
}

# Store all connection details as a JSON object so the Worker can extract each field
resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id

  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db.result
    host     = aws_db_instance.main.address
    port     = 3306
    dbname   = var.db_name
  })

  # Re-run after the DB instance is created so we have the real endpoint host
  depends_on = [aws_db_instance.main]
}

# ─── Security group ───────────────────────────────────────────────────────────

resource "aws_security_group" "rds" {
  name        = "${var.environment}-rds-sg"
  description = "Allow MySQL from backend EKS nodes only"
  vpc_id      = var.vpc_id

  ingress {
    description     = "MySQL from backend node group"
    from_port       = 3306
    to_port         = 3306
    protocol        = "tcp"
    security_groups = [var.allowed_security_group_id]
  }

  egress {
    description = "Allow all outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name        = "${var.environment}-rds-sg"
    Environment = var.environment
  }
}

# ─── DB subnet group ──────────────────────────────────────────────────────────

resource "aws_db_subnet_group" "main" {
  name        = "${var.environment}-rds-subnet-group"
  description = "Private subnets for RDS MySQL — ${var.environment}"
  subnet_ids  = var.private_subnet_ids

  tags = {
    Name        = "${var.environment}-rds-subnet-group"
    Environment = var.environment
  }
}

# ─── Parameter group ──────────────────────────────────────────────────────────

resource "aws_db_parameter_group" "mysql8" {
  name        = "${var.environment}-mysql8-params"
  family      = "mysql8.0"
  description = "MySQL 8.0 parameter group for ${var.environment}"

  # utf8mb4 supports full Unicode including emoji — good default for a book library
  parameter {
    name  = "character_set_server"
    value = "utf8mb4"
  }

  parameter {
    name  = "collation_server"
    value = "utf8mb4_unicode_ci"
  }

  tags = {
    Environment = var.environment
  }
}

# ─── RDS instance ─────────────────────────────────────────────────────────────

resource "aws_db_instance" "main" {
  identifier = "digital-library-${var.environment}"

  engine               = "mysql"
  engine_version       = "8.0"
  instance_class       = var.instance_class
  allocated_storage    = var.allocated_storage
  storage_type         = "gp3"
  storage_encrypted    = true # encrypt at rest with default KMS key

  db_name  = var.db_name
  username = var.db_username
  password = random_password.db.result

  db_subnet_group_name   = aws_db_subnet_group.main.name
  parameter_group_name   = aws_db_parameter_group.mysql8.name
  vpc_security_group_ids = [aws_security_group.rds.id]

  multi_az                    = var.multi_az
  publicly_accessible         = false # never expose the DB to the internet
  deletion_protection         = false # set to true in prod after initial setup
  skip_final_snapshot         = true  # set to false in prod
  auto_minor_version_upgrade  = true
  backup_retention_period     = var.multi_az ? 7 : 1 # 7-day backups for prod, 1 day for dev

  tags = {
    Name        = "digital-library-${var.environment}"
    Environment = var.environment
  }
}
